name: Core Tests.

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}
      - name: Install dependencies
        run: |
          pip install --upgrade --upgrade-strategy eager -e .[dev]
      - name: Run Ruff Linter
        run: ruff check  pyproject_template/ tests/ --output-format=github
      - name: Run Ruff Formatter
        run: ruff format  pyproject_template/ tests/ --diff
      - name: Run Pyright
        run: |
          pyright
      - name: Test with pytest
        run: |
          pytest
